### ISSUE TITLE
Obstacles are very challenging,

### ISSUE THREAD

**Issue by lmcrean** [lmcrean/Retro-Olympic-Sidescroller#35]
![gameplay-test-2](https://github.com/lmcrean/Retro-Olympic-Sidescroller/assets/133490867/51c8e6ec-20da-40d4-abf1-e1454dff3a2b)

![gameplay-test-1](https://github.com/lmcrean/Retro-Olympic-Sidescroller/assets/133490867/e852b857-30a5-4b39-b28c-71a5c1f0bddb)

can the obstacles be spaced out at all?

**Comment by gennadiy-gaysha** [comment]
Hi Laurie. Alena told me that she will be back in an hour and amend it
